### ISSUE TITLE
Invalid Save

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2085]
As process designer, I want to save my models as I am building them, even if they fail validation. Currently if the model validator finds an error, the Save is prevented. This impedes to save work in progress, forcing iterative saves to be valid models in of themselves which is highly inefficient. Instead, it should show a warning about the invalid design, and be unavailable to execute, but still save.

**Comment by velkymx** [comment]
I'd like to add a is_valid flag to the process database table. Only processes that have a valid is_valid value should be able to run processes.

**Comment by caleeli** [comment]
@velkymx, @marcoAntonioNina  There could be a problem saving invalid processes like this:

The BPMN validation in backend is a Consistency validation (validation with the BPMN XSD). If we skip this validation, an inconsistent process could no be loaded properly the next time it is opened. For example:

![image](https://user-images.githubusercontent.com/8028650/61462445-a4d60000-a940-11e9-8b69-14fcb2418591.png)

This process has some empty required properties (ids and references)

If we allow to save a process like that, the next time the modeler (or the engine) try to open this process, for example, the elements without ID will not be rendered because the diagram will not be able to find these elements, then these elements will remain hidden and the user will no be able to fix them causing more problems.

I think is really important that the BPMN generated by the modeler should be always a **Valid BPMN** (consistent with the XSD). There are other rules, best practices, that does not break the BPMN, like not connected elements, missing conditions, names, events,  etc. Okey we could save them, the process will not run as expected but will not crush when loading. I think the modeler should always generate a valid BPMN, if not it should be considered a bug.

So if we have an invalid BPMN first it should be sanitized before save it.

https://processmaker.slack.com/files/U078GPWPQ/FL79GK8E6/invalidbpmnproblems.mov

**Comment by velkymx** [comment]
This is implemented
