### ISSUE TITLE
Sub-Process Import Fails

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2183]
Steps to Reproduce:

Current Behavior:
The app won't respond
pm crash sub process.mp4

Expected Behavior:
A message tells the user that the app doesn't support sub processes

Sample BPMN: https://processmaker.atlassian.net/secure/attachment/59378/subprocessflow.bpmn

Video of issue:

https://processmaker.atlassian.net/secure/attachment/59375/pm%20crash%20sub%20process.mp4

**Comment by danloa** [comment]
@velkymx  The issue is old and it seems to me that is already solved:
1) The provided .bpmn file is no longer supported.
2) I've tested importing a process with a sub process. The main process is correctly imported but it is necessary to import the child process separately  and associated the call activity of the main process manually. Is this behavior correct?
