### ISSUE TITLE
Completed Forms Data

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2262]
Completed forms should use the data at the time of the form submission. Do we save the data at all for each task?

**Comment by caleeli** [comment]
@velkymx, @marcoAntonioNina  After a review and testing we decide to save all the data at the time the task is submitted (this includes the submitted data) to show a Completed Form, since the screen could use other request data (not only the submitted) to show information or calculate visibilities, etc., at that point of time.
So if we want more specific audit information we could add an additional column (`ProcessRequestToken`.`data_changed`) to save only the submitted data.

**Comment by caleeli** [comment]
@velkymx  Yes, actually the data is saved at the time of form submission for each task (into process_request_token) so the Completed Forms show the information at that time:

![CompletedForms](https://user-images.githubusercontent.com/8028650/64029843-60c74500-cb13-11e9-90cd-766de13fe380.gif)
