### ISSUE TITLE
transfer old processmaker 3.6 applications

### ISSUE THREAD

**Issue by hdshariati** [ProcessMaker/processmaker#2469]
hi
I want migrate to pm4.
how can I transfer old applications in pm3.6 ?

**Comment by tdondich** [comment]
We don't support ease of transfering old application from 3.x to 4 at this time just due to the enormous amount of changes in the platform.  More information about your processes/applications can help us guide you to the next steps you might want to take. Please share them and we'll see what info we can provide.

**Comment by hmdshariati** [comment]
[tours-2.zip](https://github.com/ProcessMaker/processmaker/files/4419066/tours-2.zip)
this is pmx compressed file of real processmaker 3 workflow @tdondich
