### ISSUE TITLE
Timeout Modal Progress Bar

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2562]
It should start at 100% and go down from there. Currently starts at 50%

**Comment by ryancooley** [comment]
Unable to reproduce. The percentage displayed is calculated based on the amount of time we give users to see the warning before the session is ended (default: 60 seconds) minus the amount of time they have left. If the warning comes up later than it should due to a client-side issue, a user may see a progress bar at 50%, but the warning should come up with 60 seconds left.

![session](https://user-images.githubusercontent.com/867714/69354874-afc5d780-0c35-11ea-82c2-fa5dc205877a.gif)

**Comment by ryancooley** [comment]
Unable to reproduce
