### ISSUE TITLE
Import screens not working

### ISSUE THREAD

**Issue by bmackley** [ProcessMaker/processmaker#2700]
Cannot import a new screen. Tested in RC1 and RC2 with no luck. 
https://drive.google.com/file/d/1dGH9oufvvUmhJMvKTsLCd0j4iqhDyl2O/view?usp=sharing

**Comment by nolanpro** [comment]
@bmackley This is probably because a screen exported in one version of PM4 usually can not be imported into a different version. Just to check, can you successfully export and then re-import a screen on the same instance? Please attach the exported screen you tested in the video here. Actually looks like exporting on staging-pm4qa.processmaker.net isn't working right now. Can you try on a different server? Thanks

**Comment by bmackley** [comment]
@nolanpro I successfully was able to export from one instance to another (same instance). Thanks, closing the issue.
