### ISSUE TITLE
undefined postinstall

### ISSUE THREAD

**Issue by Kamoba** [ProcessMaker/processmaker#2734]
I'm trying to install ProcessMaker locally on windows 10.
I installed first :
 • Virtualbox 6.10, 
 • Vagrant 2.2.6, 
 • XAMPP 7.2.26.0
 • Composer 1.9.1
 • Node.js v13.6.0

1. composer install
2. composer install --ignore-platform-reqs
3. **npm install**

in order to fix ERROR: checking for Python executable "python2" in the PATH ...
i did: 
> npm --add-python-to-path='true' --debug install --global windows-build-tools
> npm install --global node-gyp

Now when i'm doing **npm install** or npm install  --unsafe-perm=true i got this:

> λ npm install

> \> undefined postinstall C:\Users\kamoba\Downloads\processmaker-develop
> \> mkdir -p public/css/precompiled && cp -rf node_modules/npm-font-open-sans public/css/precompiled/npm-font-open-sans && cp -rf node_modules/bootstrap/scss public/css/precompiled/bootstrap && cp -rf node_modules/@fortawesome/fontawesome-free public/css/precompiled/fontawesome-free && cp -rf node_modules/vue-multiselect/dist/vue-multiselect.min.css public/css/precompiled

>The syntax of the command is incorrect.
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! undefined postinstall: `mkdir -p public/css/precompiled && cp -rf node_modules/npm-font-open-sans public/css/precompiled/npm-font-open-sans && cp -rf node_modules/bootstrap/scss public/css/precompiled/bootstrap && cp -rf node_modules/@fortawesome/fontawesome-free public/css/precompiled/fontawesome-free && cp -rf node_modules/vue-multiselect/dist/vue-multiselect.min.css public/css/precompiled`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the undefined postinstall script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\kamoba\AppData\Roaming\npm-cache\_logs\2020-01-14T17_25_39_222Z-debug.log

Thanks

**Comment by baptistepattyn** [comment]
I am having the same error

I can confirm i have following software versions installed on my system:

- Virtualbox 5.2 or above
- Vagrant 2.2.0 or above
- PHP 7.2.0 or aboe
- Composer
- Node.js 10.13.0 or above


Full debug log and cmd printout can be found below

Debug log: (error starts at line 57946
[2020-02-14T07_51_05_957Z-debug.log](https://github.com/ProcessMaker/processmaker/files/4203362/2020-02-14T07_51_05_957Z-debug.log)

CMD printout:
[cmd printout processmaker error.txt](https://github.com/ProcessMaker/processmaker/files/4203368/cmd.printout.processmaker.error.txt)

**Comment by baptistepattyn** [comment]
Okay after some investigating i found the issue.
There were two issues with the command:

**1. Firstly**
The -rf argument that is added to the cp command is not valid so needs to be removed. You can do this inside VSCode or any other editor.

**2. Secondly**
The postinstall command is a concatenation of multiple CLI commands (one mkdir and a few cp command). When running all of the commands one after another in the processmaker folder using powershell I had no errors, so the commands are working by themselves. Then I ran the entire postinstall command
`mkdir -p public/css/precompiled && cp node_modules/npm-font-open-sans public/css/precompiled/npm-font-open-sans && cp node_modules/bootstrap/scss public/css/precompiled/bootstrap && cp node_modules/@fortawesome/fontawesome-free public/css/precompiled/fontawesome-free && cp node_modules/vue-multiselect/dist/vue-multiselect.min.css public/css/precompiled`

This gave me the following error:
`The token '&&' is not a valid statement separator in this version.`

**Fixes for the invalid statement separator**

1. Alter the postinstall command in the package.json file to be empty so:
'"postinstall": "",`
  And then run the commands separately in powershell

2.  Run in cmd instead of powershell

**Comment by Kamoba** [comment]
I think I managed to get past this error by modifying the package.json file, replacing all the "/" with "\\" on the "postinstall" command.
But something went wrong with the next steps so I gave up.
Next time I'll try your method. Maybe it'll make a difference.

Thanks!

**Comment by mohammadjebrahimi** [comment]
its work for me

mkdir public\\css\\precompiled && cp -rf node_modules\\npm-font-open-sans public\\css\\precompiled\\npm-font-open-sans && cp -rf node_modules\\bootstrap\\scss public\\css\\precompiled\\bootstrap && cp -rf node_modules\\@fortawesome\\fontawesome-free public\\css\\precompiled\\fontawesome-free && cp -rf node_modules\\@processmaker\\vue-multiselect\\dist\\vue-multiselect.min.css public\\css\\precompiled
