### ISSUE TITLE
Package: Versioning

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2844]
Repo: 

https://github.com/ProcessMaker/package-versions

PRD:

https://processmaker.atlassian.net/wiki/spaces/PM4/pages/584908838/Versioning

Requires the Hooks PR #3011

**Comment by PMQABen** [comment]
Error during installation:
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In PluginServiceProvider.php line 82:

Call to undefined method ProcessMaker\Http\Controllers\Process\ScreenController::registerAddon()                                                        

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
```

**Comment by PMQABen** [comment]
* **Bug** Save button for Screen Builder is missing with this package installed
* **Bug** Cannot see what was changed between versions
* *Suggestion* - Unable to see the optional description for a saved edit, unless the user chooses "copy to latest"
* *Suggestion* - The same layout is used for "name this version" and "copy to latest", nothing differentiates the two display.
* *Suggestion* - The initial version for Process/Script/Screen has no name or description. Maybe we should have a default subject of "first load" or "blank state" or "initial creation" for the first version, since all saved versions thereafter will prompt the user for a subject.

**Comment by marcoAntonioNina** [comment]
@PMQABen in the Hooks PR #3011, need 
need to compile with **npm run dev**, There are changes in the vue components.

**Comment by PMQABen** [comment]
I have to re-open this ticket. Email and Display screens are not prompting the user with the Version modal.

**Comment by PMQABen** [comment]
Latest update (not noted in ticket), fixed the icon and modal issues. The "outline" icon will now show up for save when this package is installed, and Email/Display screens also now properly prompt the user with the version change modal.

**Comment by PMQABen** [comment]
**Reopening ticket**
In Firefox, Safari, and MS Edge (Chromium), the version change modal does not disappear after saving.
