### ISSUE TITLE
Pusher Payload Size

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2857]
After debugging with Summer Kay we found the issue to be the payload size going to pusher:

```
[2020-02-07 00:31:23] production.ERROR: The data content of this event exceeds the allowed maximum (10240 bytes). See https://pusher.com/docs/channels/server_api/http-api#publishing-events for more info
 {"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): The data content of this event exceeds the allowed maximum (10240 bytes). See https://pusher.com/docs/channels/server_api/http-api#publishing-events for more inf
```

After moving her back to local laravel-echo-server for socket.io, it is now working as expected.

Would we be able to get the payload size optimized or chunked so that it pusher.io can handle the requests coming in? Let me know what you think.

**Comment by tdondich** [comment]
I am teh working on eet.

**Comment by tdondich** [comment]
@velkymx It appears to be more of a problem of the events related to process/request including the serialized model for request and/or token.  

I don't want to modify these events directly because I know @caleeli will be more familiar with the listeners for these events.  But they should only include the ids of the resources and the listeners for these events (both backend and frontend) should fetch the resource from the backend either through eloquent or api.

Going to leave this until it's picked up by someone else.
