### ISSUE TITLE
Abandoned Packages

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2980]
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.

Update to these alternative packages

**Comment by nolanpro** [comment]
These abandon and out of date packages are set requirements for Laravel 5. We would have to upgrade to Laravel 6, then 7, to update them all to the latest stable versions.

This is definitely something we should do. Hopefully sooner rather than later, since upgrading and testing framework stuff gets harder the more we diverge from the latest stable release. But it would definitely take some time and effort to do.
