### ISSUE TITLE
ProcessMaker V4.0.5 Community Edition Production Installation Guide

### ISSUE THREAD

**Issue by DanieRautenbach** [ProcessMaker/processmaker#3206]
Hello there

We (our company) are very keen to move forward with ProcessMaker V4 Community Edition. 
We have tested on PM3.3 (Bitnami) and 3.4 (CE bare installations on Windows and Linux) 
Instead of investing a lot of time and energy into designing for Version 3 and then migrating to Version 4, we hope to start most of the process design in Version 4.

Unfortunately, running a development environment for our production is not really an option.

I have spent a couple of days attempting to find a guide to get PM4 CE installed on a bare Ubuntu or Windows base, without any success. All the guides are for development environments.

**Would it be possible to produce an easy to follow production installation guide for non-developers?**

I tried to follow the method described in https://github.com/ProcessMaker/processmaker/issues/3135 ,but got stuck in database creation. 
(I am also not sure where chau-huu obtained these instructions to start with, maybe the guide exists  but I have somehow managed to miss it in all my searches.)

Your help greatly appreciated.

My thanks
Danie

**Comment by rmacordeiro** [comment]
Hi, I'm also looking for that guide.
If you find something, please share.

Thank you

**Comment by shrike71** [comment]
Also running into problems with this. Tried to get it running with both PostGres (desired) and MariaDB. With the Postgres version, i ran into loads of compatibility issues with the ->json() column Builder type. When we attempted MariaDB, we experienced the reverse, which we were able to fix by manually converting the migrations to ->text(). When logging the output we are noticing several functions that seem to be postgres specific being executed (and failing) in the UI, even though the database driver was specifically set to 'mysql'. Also, npm install and npm run dev failed multiple times due to deprecated and retired modules, which i (mostly) was able to fix, but I'm not sure of the implications in the application.

We're currently trying to evaluate the use of PM4 for a hopeful migration of our treasury and accounting ops, but so far, the only things we've been able to get working without visible issues are logging in, and creating categories

Environments attempted:
Ubuntu 18.04
PostGres 12 or MariaDB 10
Nginx / phpfpm 7.2, 7.3 and 7.4
Nodejs 12

I am attempting a new install on new VM boilerplates later on today. I will post screenshots of the progress and operation

**Comment by bcando** [comment]
Keen to hear how you go, @shrike71.

I encountered similar issues with npm install and npm run dev.... After working through these and running the install, everything says it is installed successfully.

But it doesn't... 

Checking the logs I get a single entry:
local.NOTICE: Unable to register gates. Either no database connection or no permissions table exists.

Navigating to the site I just get a 404 error, but interestingly it is trying to redirect me to /login...

**Comment by tdondich** [comment]
Hi @shrike71 . We haven't fully performed enough testing on postgres to give it full support as our enterprise clouds do run MySQL in an AWS env.  I think we'd be eager to get any PRs to better support Postgres and MariaDB.  I would say changing the migrations to text wouldn't be great.  The request data should be stored as json columns as we do json based searching through it.  When you change the database driver, it's imperative to make sure you clear the config cache to make sure the database connection is properly configured.  I would assume that you ran into this because you tried postgres first.  So do a "php artisan config:clear" to clear that up and let us know.

@bcando , be sure you run the initial migrations/etc.  I think the install command should perform all of this for you.

And just a note, we don't formally support the open source version for production environments. We would highly recommend utilizing our SaaS based cloud services in order to provide production support.  This, however, doesn't stop any potential PRs to make utilizing the open source version easier. I'm eager to hear more suggestions on how to improve this.

**Comment by nukes88** [comment]
Is a production installation guide in the works?

**Comment by DanieRautenbach** [comment]
Hi Nuke88

Unfortunately I have had no feedback regarding my original request / query.

Regards
Danie

**Comment by allanregistos** [comment]
> Hello there
> 
> We (our company) are very keen to move forward with ProcessMaker V4 Community Edition.
> We have tested on PM3.3 (Bitnami) and 3.4 (CE bare installations on Windows and Linux)
> Instead of investing a lot of time and energy into designing for Version 3 and then migrating to Version 4, we hope to start most of the process design in Version 4.
> 
> Unfortunately, running a development environment for our production is not really an option.
> 
> I have spent a couple of days attempting to find a guide to get PM4 CE installed on a bare Ubuntu or Windows base, without any success. All the guides are for development environments.
> 
> **Would it be possible to produce an easy to follow production installation guide for non-developers?**
> 
> I tried to follow the method described in #3135 ,but got stuck in database creation.
> (I am also not sure where chau-huu obtained these instructions to start with, maybe the guide exists but I have somehow managed to miss it in all my searches.)
> 
> Your help greatly appreciated.
> 
> My thanks
> Danie
I managed to run the 4.0.7 (latest released as of 7.28.2020. After many headaches, I was able to run it under apache. The configuration from pm3(pmos.conf) is almost the same, with the exception of pm4's laravel, composer, docker requirements. I don't about the latter, but, I think I do not need docker, since I only want the laravel app to run under apache.

Having said this, the application is terribly slow. I know that there are ways to optimize it, but it's not worth the effort, much less I am not capable of doing the optimization. I search google on why laravel app is really slow, then there are answers I've found defending laravel or there are tweaks to optimize it like "php artisan optimize" something along that line.

If you really want to have a pm4 optimize for production purposes, I think the enterprise edition is the way to go. Of course, if you can improve the PM4 performance on par witn PM3 and share it with us, you are so welcome.

If anything, my advice is to **"stay"** with PM3 for now. PM4 might have good features, but laravel, for Pete's sake, stay with PM3.

In my google search that lands on stackoverflow, someone recommended that the VM machine must be hosted on a "memory optimized" compute engine. But we do not have _that_ luxury. I don't think it is a good idea to create a PHP framework that is horribly slow by default and the solution is just to use an expensive compute engine just to make things better.

Just my 2 cents.

**Comment by DanieRautenbach** [comment]
Thank you Allan, so noted

**Comment by allanregistos** [comment]
Docker is needed for the script executor(A new PM4 feature) to work. And so, docker is a "must" requirement for PM4.

See:
https://processmaker.gitbook.io/processmaker/processmaker-administration/script-executor-management/what-is-a-script-executor

**Comment by velkymx** [comment]
The readme has been updated with lasted requirements. We recommend you use the latest build as many of the deployment issues have been ironed out.
