### ISSUE TITLE
pion/laravel-chunk-upload dev-master conflict in composer.json

### ISSUE THREAD

**Issue by hmdshariati** [ProcessMaker/processmaker#3623]
**Composer install conflict**
when I pulled v4.0.x and ran composer install this error has appeared.

**To Reproduce**
1. make new clone of repository
2. try to run composer install
3. See error

**Expected behavior**
successfull vendor install with composer.

**Desktop :**
 - OS: Linux Ubuntu 20
 - Browser  firefox
**Additional context**

**Comment by burton314** [comment]
The composer.require file refers to "pion/laravel-chunk-upload":"dev-master".
I changed "dev-master" to version "1.2.9" as this version was compatible with laravel/framework 5.8
and 5.8 is required in the current processmaker download.

Then I removed the following entry in composer.require so that composer wouldn't ask for the latest laravel-chunk-upload version from processmaker:

"repositories": [{
        "type": "vcs",
        "url": "https://github.com/ProcessMaker/laravel-chunk-upload"
    }],

Then composer update and following install worked fine.
