### ISSUE TITLE
API PROCESSMAKER 4.1.0

### ISSUE THREAD

**Issue by agustin-modia-agp** [ProcessMaker/processmaker#3802]
![Captura de Pantalla 2021-05-15 a la(s) 00 53 04](https://user-images.githubusercontent.com/84145433/118347258-1a4c9080-b518-11eb-9d4b-339d54546ee3.png)
![Captura de Pantalla 2021-05-15 a la(s) 00 54 01](https://user-images.githubusercontent.com/84145433/118347260-1b7dbd80-b518-11eb-8753-727cd07c8b1f.png)

API PROCESSMAKER  version 4.1.0 AND 4.1.18

hello good afternoon, I have a problem with the APIs, either doing the try out from swangger or consuming the API from other code, the error that comes out is unauthenticated, I already tried passing the token of the admin user in the field of pm_api_bearer and also automatically from swagger that is redirected to processmaker for login approval.

To connect or test the api I use the processmaker documentation, which uses https://staging-pm4.processmaker.net/api/documentation.
obviously applied to my server https: {server ip of my processmaker} / api / documentation. In the swagger I can log in perfectly using the authorize button, but when I want to try an api in the same place, the result I have is the following:

Error: Unauthorized

I have also tried the api through the console, with curl, passing it the user token created in the processmaker, as the processmaker wiki says on github (https://github.com/ProcessMaker/processmaker/wiki/API-Authentication) but I get the same result.

Curl example:

$ export TOKEN = “your generated token”
$ curl -H ‘Accept: application / json’ -H “Authorization: Bearer $ {TOKEN}” {server ip of my processmaker}

in the token in the curl or in the pm_api_bearer (http, Bearer) (PREVIOUS SCREENSHOTS). I introduce the token generated by processmaker in the path admin -> user -> API TOKEN.

![Captura de Pantalla 2021-05-15 a la(s) 00 56 55](https://user-images.githubusercontent.com/84145433/118347292-79120a00-b518-11eb-9ae3-bafaf180ffb6.png)

**Comment by agustin-modia-agp** [comment]
@velkymx

**Comment by agustin-modia-agp** [comment]
@boliviacoca

**Comment by agustin-modia-agp** [comment]
@tomolimo

**Comment by velkymx** [comment]
@agustin-modia-agp two points:

1. Make sure the user consuming the API has permission to use it.
2. Make sure that your application installation has the encryption key defined properly

**Comment by agustin-modia-agp** [comment]
Hello @velkymx  ,

Thank you in advance for your answer.
Regarding the 2 points mentioned, first point: if the user with whom I am working is the user armin with all the given privileges, I have also created different users to test and the result is the same.
and on the second point I am using a virtual machine in bitnami vmware. I have tested the virtual machine with both processmaker 4.1.0 and processmaker 4.1.18. And the result is the same, if you could give me any other information or solution, I would appreciate it.

Greetings.

**Comment by mindfullofit** [comment]
@agustin-modia-agp Hope all is well. I saw in the Bitnami Community forum where you posted this question but could not respond since it is currently closed. Since you are using the Bitnami Stack, please know that the Apache configuration is stripping the Authorization header. So, even though you are able to get an access token using OAuth2, you will receive the 401 error. To fix it, you will need to adjust either your .htaccess file or modify your processmaker-vhost.conf file. The .conf file is located in your server at /opt/bitnami/apache2/conf/vhosts . There is also one for the SSL version of the application. 
Here's an example of how to modify the .htaccess on [SO](https://stackoverflow.com/questions/39295407/401-unauthorised-using-a-bearer-token-with-laravel-passport) . Best wishes!
